version: '2'
services:
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  php:
    build: ./docker/php-fpm
    links:
      - db
    extra_hosts:
      - "docker.host:127.0.0.1"
    volumes:
      - ./:/var/www/symfony:cached
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: symfony
      DATABASE_USER: symfony
      DATABASE_PASSWORD: symfony
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx:cached
